### PR TITLE
Remove non-determinism from integration test workflow

### LINKED ISSUE #409: Integration test workflow fails non-deterministically
**Describe the bug**
Sometimes when all tests pass locally, the integration test workflow fails on CI, but then passes when re-run.

**Expected behavior**
Given the same code, the workflow should always pass or always fail, in a deterministic way.

**Output**
Sample 1: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/actions/runs/16125105887/job/45500036344?pr=388
```
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
❌ end-to-end test Test background tracking can be easily disabled on first use, to satisfy Google/Apple requirements (failed)
adb uninstall failed: ProcessException: Process exited abnormally with exit code 1:
Failure [DELETE_FAILED_INTERNAL_ERROR]
  Command: /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 uninstall com.example.mosquito_alert_app

Error: 0 tests passed, 1 failed.
Error: The process '/usr/bin/sh' failed with exit code 1
Terminate Emulator
INFO         | Wait for emulator (pid 3024) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)

USER_INFO    | Snapshots have been disabled by the user, save request is ignored.
ERROR        | stop: Not implemented
WARNING      | Emulator client has not yet been configured.. Call configure me first!
I0707 18:49:46.908122    3024 VkDecoderGlobalState.cpp:2421] Destroyed VkDevice:0x559dde13e010
I0707 18:49:46.908179    3024 VkDecoderGlobalState.cpp:9181] Destroyed VkInstance:0x559dd89a8000 for application:Impeller engine:Impeller.
```

Sample 2: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/actions/runs/16138679753/job/45540803533
```
3 warnings
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
❌ loading /home/runner/work/Mosquito-Alert-Mobile-App/Mosquito-Alert-Mobile-App/integration_test/background_tracking_easily_disabled_test.dart (failed)

Error: 0 tests passed, 1 failed.
Error: The process '/usr/bin/sh' failed with exit code 1
Terminate Emulator
INFO         | Wait for emulator (pid 2990) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)

USER_INFO    | Snapshots have been disabled by the user, save request is ignored.
ERROR        | stop: Not implemented
WARNING      | Emulator client has not yet been configured.. Call configure me first!
```

### PR DESCRIPTION
**Pull request by DigitalSeneca**
fixes #409 

The integration test was failing too frequently in a non-deterministic way due to a 12 minute timeout.
The step "Run integration tests" was building the app + running the steps, and in some cases this would take 13 or 14 minutes while in most cases it was under 12 minutes.

## Changes
- Divide workflow into two steps (build app) and (run tests) so that they don't surpass 12 minutes (github actions timeout for a single step).
- When env is "test", skip async logic: `workmanager`, `backgroundTracking`, `syncReports`, `checkForUnfetchedData`
- Add waitForWidget() method on integration test that solves `Failure [DELETE_FAILED_INTERNAL_ERROR]`

## Testing result with 15 runs:
Screenshot 2025-07-15 at 09 16 23

### CODE REVIEW

File: android/gradle.properties [hunk 1]
```diff
@@ -5,4 +5,5 @@ android.enableJetifier=true
 org.gradle.warning.mode=all
 android.defaults.buildfeatures.buildconfig=true
 android.nonTransitiveRClass=false
-android.nonFinalResIds=false
\ No newline at end of file
+android.nonFinalResIds=false
+org.gradle.jvmargs=-Xmx4096m
```
Comment (DigitalSeneca) [inline android/gradle.properties:9]: add more resources to avoid gradle going out of memory during CI execution

File: integration_test/background_tracking_easily_disabled_test.dart [hunk 2]
```diff
@@ -4,6 +4,20 @@ import 'package:integration_test/integration_test.dart';
...
+}) async {
+  final end = DateTime.now().add(timeout);
+  while (DateTime.now().isBefore(end)) {
+    await tester.pump();
+    if (finder.evaluate().isNotEmpty) return;
+    await Future.delayed(const Duration(milliseconds: 100));
+  }
+  throw Exception('Widget not found: $finder');
+}
+
```
Comment (DigitalSeneca) [inline integration_test/background_tracking_easily_disabled_test.dart:20]: Solves the bug described in `Sample 1` of #409 

```
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000338000
../../third_party/SwiftShader/src/Vulkan/VkPhysicalDevice.cpp:649 WARNING: UNSUPPORTED: curExtension->sType: 1000437000
❌ end-to-end test Test background tracking can be easily disabled on first use, to satisfy Google/Apple requirements (failed)
adb uninstall failed: ProcessException: Process exited abnormally with exit code 1:
Failure [DELETE_FAILED_INTERNAL_ERROR]
  Command: /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 uninstall com.example.mosquito_alert_app

Error: 0 tests passed, 1 failed.
Error: The process '/usr/bin/sh' failed with exit code 1
```

File: .github/workflows/integration_tests.yml [hunk 3]
```diff
@@ -40,11 +40,18 @@ jobs:
         adb uninstall com.example.mosquito_alert_app || true
         adb emu kill || true
 
+      # The timeout for a single step in Github Actions is 12 minutes
+    - name: Build debug appbundle (avoids test loader timeouts)
+      run: flutter build appbundle --debug
+
```
Comment (DigitalSeneca) [inline .github/workflows/integration_tests.yml:46]: Solves the bug described in `Sample 2` of #409
