### PR TITLE
Bug fix: My reports Bites showing incorrect location

### LINKED ISSUE #560: My reports shows incorrect location
It shows something like "Location: Head" but it should be "Location: Barcelona"

Only for Europe: Backend returns location
Also available: getCityFromCoords

### PR DESCRIPTION
**Pull request by DigitalSeneca**
fixes #560 

Screenshot 2025-10-24 at 11 40 49
Screenshot 2025-10-24 at 11 36 01

### CODE REVIEW

File: lib/pages/my_reports_pages/components/reports_list_bites.dart [hunk 1]
```diff
@@ -62,32 +62,23 @@ class _ReportsListBitesState extends State<ReportsListBites> {
     return DateFormat('yyyy-MM-dd HH:mm').format(report.createdAt.toLocal());
```
Comment (epou) [inline lib/pages/my_reports_pages/components/reports_list_bites.dart]: createdAtLocal
